# Generated by Django 5.2.11 on 2026-02-07 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('detected_pattern', models.TextField(help_text='Description of the anomaly/pattern the agent found in meter data')),
                ('detection_data', models.JSONField(default=dict, help_text='Raw analysis data: spike times, magnitudes, baselines, etc.')),
                ('user_hypothesis', models.TextField(help_text='What the user thinks is causing the pattern')),
                ('plan_summary', models.TextField(help_text='Short summary of the plan')),
                ('plan_details', models.JSONField(default=dict, help_text='Structured plan with specific actions and expected outcomes')),
                ('baseline_daily_kwh', models.FloatField(help_text='Average daily consumption at time of plan creation')),
                ('baseline_peak_kwh', models.FloatField(help_text='Average daily peak-period consumption at plan creation')),
                ('baseline_monthly_cost_fils', models.IntegerField(help_text='Estimated monthly cost at plan creation')),
                ('status', models.CharField(choices=[('active', 'Active'), ('monitoring', 'Monitoring'), ('verified', 'Verified'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('verify_after_date', models.DateField(help_text='Date when the agent should check results')),
                ('verification_result', models.JSONField(blank=True, help_text='Comparison of baseline vs actual after monitoring period', null=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='accounts.subscriber')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('check_date', models.DateField()),
                ('avg_daily_kwh', models.FloatField()),
                ('avg_peak_kwh', models.FloatField()),
                ('avg_offpeak_kwh', models.FloatField()),
                ('estimated_cost_fils_per_day', models.IntegerField()),
                ('change_vs_baseline_percent', models.FloatField(help_text='Negative = improvement (less consumption)')),
                ('notes', models.TextField(blank=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='plans.optimizationplan')),
            ],
            options={
                'ordering': ['-check_date'],
            },
        ),
    ]
