# Generated by Django 5.2.11 on 2026-02-07 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription_number', models.CharField(db_index=True, help_text='JEPCO subscription number from electricity bill, e.g., 01-123456-01', max_length=20, unique=True)),
                ('phone_number', models.CharField(db_index=True, help_text='WhatsApp phone in E.164 format: +962791234567', max_length=20, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('language', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], default='ar', max_length=2)),
                ('tariff_category', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('agricultural', 'Agricultural'), ('ev_home', 'EV Home Charging')], default='residential', max_length=30)),
                ('governorate', models.CharField(default='Amman', help_text='JEPCO service area: Amman, Zarqa, Madaba, or Balqa', max_length=50)),
                ('area', models.CharField(blank=True, help_text='Neighborhood, e.g., Abdoun, Sweifieh, Jubeiha', max_length=100)),
                ('household_size', models.IntegerField(blank=True, null=True)),
                ('has_ev', models.BooleanField(default=False)),
                ('has_solar', models.BooleanField(default=False)),
                ('home_size_sqm', models.IntegerField(blank=True, help_text='Approximate home size', null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('wants_weekly_report', models.BooleanField(default=True)),
                ('wants_spike_alerts', models.BooleanField(default=True)),
                ('wants_plan_checkups', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
