# Generated by Django 6.0.2 on 2026-02-16 18:53

from django.db import migrations


def update_phone(apps, schema_editor):
    Subscriber = apps.get_model("accounts", "Subscriber")
    Subscriber.objects.filter(
        subscription_number="01-100001-01",
        phone_number="+962791000001",
    ).update(phone_number="+962798494038")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_subscriber_user'),
    ]

    operations = [
        migrations.RunPython(update_phone, migrations.RunPython.noop),
    ]
