# Generated by Django 6.0.2 on 2026-02-15 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_subscriber_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(default='ar', max_length=2)),
                ('last_intent', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_sessions', to='accounts.subscriber')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_message', models.TextField()),
                ('agent_response', models.TextField()),
                ('intent', models.CharField(blank=True, max_length=30)),
                ('tools_called', models.JSONField(default=list)),
                ('language', models.CharField(default='ar', max_length=2)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='agent.conversationsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriberNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('appliance', 'Appliance'), ('schedule', 'Schedule'), ('preference', 'Preference'), ('household_fact', 'Household Fact'), ('goal', 'Goal')], max_length=20)),
                ('content', models.TextField(help_text='Stored in English for consistency')),
                ('is_active', models.BooleanField(default=True)),
                ('source_turn', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_created', to='agent.conversationturn')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='accounts.subscriber')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversationsession',
            index=models.Index(fields=['subscriber', '-created_at'], name='agent_conve_subscri_df12af_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationsession',
            index=models.Index(fields=['is_active'], name='agent_conve_is_acti_dfda0e_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationturn',
            index=models.Index(fields=['session', 'created_at'], name='agent_conve_session_3bcd77_idx'),
        ),
        migrations.AddIndex(
            model_name='subscribernote',
            index=models.Index(fields=['subscriber', 'is_active', '-created_at'], name='agent_subsc_subscri_6bed67_idx'),
        ),
        migrations.AddIndex(
            model_name='subscribernote',
            index=models.Index(fields=['subscriber', 'category'], name='agent_subsc_subscri_204684_idx'),
        ),
    ]
