# Generated by Django 5.2.11 on 2026-02-07 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('kwh', models.FloatField(help_text='Energy consumed in this interval (kWh)')),
                ('voltage', models.FloatField(blank=True, help_text='Voltage in volts', null=True)),
                ('current_amps', models.FloatField(blank=True, null=True)),
                ('power_factor', models.FloatField(blank=True, null=True)),
                ('power_kw', models.FloatField(help_text='Average power draw in kW for this interval (kwh * 4 for 15-min intervals)')),
                ('tou_period', models.CharField(choices=[('off_peak', 'Off-Peak'), ('partial_peak', 'Partial Peak'), ('peak', 'Peak')], max_length=20)),
                ('is_simulated', models.BooleanField(default=True, help_text='True = synthetic demo data')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='accounts.subscriber')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['subscriber', 'timestamp'], name='meter_meter_subscri_547d62_idx'), models.Index(fields=['subscriber', 'tou_period', 'timestamp'], name='meter_meter_subscri_48535e_idx')],
                'unique_together': {('subscriber', 'timestamp')},
            },
        ),
    ]
